name: Workflow Run Test (Event)

on:
  push:
    branches:
      - main

jobs:
  example-app:
    name: Example Application Pipeline
    strategy:
      matrix:
        fixed-sleep: [1, 2]
        random-sleep: [1, 2]
    uses: ./.github/workflows/example-app-workflow.yml
    with:
      fixed-sleep: ${{ matrix.fixed-sleep }}
      random-sleep: ${{ matrix.random-sleep }}
